config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :banks, except: [:show, :destroy] do
      put :toggle_activation, on: :member
    end
  end
  resources :payments, only: :update
  get '/content/bank_transfer', to: 'content#bank_transfer', as: :bank_transfer_instructions
end

app/models/spree/bank.rb
module Spree
  class Bank < ActiveRecord::Base
    validates :name, :account_no , presence: true
    validates_uniqueness_of :account_no , scope: :name

    scope :active, -> { where(active: true) }
  end
end

app/models/spree/order_decorator.rb
module Spree
  Order.class_eval do
    self.whitelisted_ransackable_associations += %w(payments)
  end
end

app/models/spree/payment_decorator.rb
Spree::Payment.class_eval do
  attr_accessor :validate_bank_details
  validates :bank_name, :account_no, :transaction_reference_no, :deposited_on, presence: true, if: :validate_bank_details

  scope :from_bank_transfer, -> { joins(:payment_method).where(spree_payment_methods: { type: 'Spree::PaymentMethod::BankTransfer' }) }

  self.whitelisted_ransackable_attributes = %w( transaction_reference_no state )

  def details_submitted?
    transaction_reference_no?
  end

  def to_param
    number.presence.to_s
  end
end

app/models/spree/payment_method/bank_transfer.rb
module Spree
  class PaymentMethod::BankTransfer < PaymentMethod

    def actions
      %w{capture void}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)
      simulated_successful_billing_response
    end

    def void(*args)
      simulated_successful_billing_response
    end

    def source_required?
      false
    end

    def credit(*args)
      simulated_successful_billing_response
    end

    private

    def simulated_successful_billing_response
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end
  end

end

app/models/spree/user_decorator.rb
module Spree
  User.class_eval do
    has_many :payments, through: :orders
  end
end

app/controllers/spree/admin/banks_controller.rb
module Spree
  module Admin
    class BanksController < ResourceController
      def index
        @banks = Spree::Bank.page(params[:page])
      end

      def toggle_activation
        @success = @bank.toggle!(:active)
      end
    end
  end
end

app/controllers/spree/admin/payments_controller_decorator.rb
 module Spree
   module Admin
     PaymentsController.class_eval do

       private

       def load_payment
         @payment = Payment.find_by!(number: params[:id])
       end
     end
   end
 end

app/controllers/spree/content_controller_decorator.rb
module Spree
  ContentController.class_eval do
    def bank_transfer
      render layout: false
    end
  end
end

app/controllers/spree/payments_controller.rb
module Spree
  class PaymentsController < Spree::StoreController
    before_action :authenticate_spree_user!
    before_action :find_payment

    def update
      payment_details = PaymentDetails.new(@payment, payment_params)
      if payment_details.save
        flash[:notice] = Spree.t(:payment_successfully_updated)
      else
        flash[:error] = payment_details.errors.to_sentence
      end
      redirect_back fallback_location: :back
    end

    def find_payment
      @payment = spree_current_user.payments.find_by(number: params[:id])
      unless @payment
        flash[:error] = Spree.t(:payment_not_found)
        redirect_back fallback_location: :back
      end
    end

    private

    def payment_params
      params.require(:payment).permit(:deposited_on, :bank_name, :account_no, :transaction_reference_no)
    end
  end
end

app/helpers/spree/admin/banks_helper.rb
module Spree
  module Admin
    module BanksHelper

      def bank_status(bank)
        bank.active? ? Spree.t(:active) : Spree.t(:inactive)
      end

      def action_to_toggle_bank_status(bank)
        bank.active? ? Spree.t(:deactivate) : Spree.t(:activate)
      end

      def action_text_to_toggle_bank_status(bank)
        bank.active? ? 'remove-sign' : 'ok-sign'
      end

    end
  end
end

app/views/spree/admin/banks/_form.html.erb
<div class="row js-banks-form">
  <div class="col-10">
    <div data-hook="admin_zone_form_fields">
      <fieldset class="no-border-bottom">
        <%= bank_form.field_container :name do %>
          <%= bank_form.label :name %> <span class="required">*</span><br />
          <%= bank_form.text_field :name, class: 'fullwidth' %>
        <% end %>

        <%= bank_form.field_container :account_no do %>
          <%= bank_form.label :account_no %> <span class="required">*</span><br />
          <%= bank_form.text_field :account_no, class: 'fullwidth' %>
        <% end %>

        <%= bank_form.field_container :additional_details do %>
          <%= bank_form.label :additional_details %><br />
          <%= bank_form.text_area :additional_details, rows: 10, class: 'fullwidth' %>
        <% end %>

        <%= bank_form.field_container :active, class: ['checkbox'] do %>
          <%= bank_form.label :active do %>
            <%= bank_form.check_box :active %>
            <%= Spree.t(:active) %>
          <% end %>
        <% end %>
      </fieldset>
    </div>
  </div>
</div>

app/views/spree/admin/banks/edit.html.erb
<% admin_breadcrumb(t('spree.settings')) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::Bank), spree.admin_zones_path) %>
<% admin_breadcrumb(@bank.name) %>


<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @bank } %>

<%= form_for [:admin, @bank] do |bank_form| %>
  <%= render partial: 'form', locals: { bank_form: bank_form } %>
  <div class="clear"></div>
  <%= render partial: 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/banks/index.html.erb
<% admin_breadcrumb(t('spree.settings')) %>
<% admin_breadcrumb(plural_resource_name(Spree::Bank)) %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Zone) %>
    <li>
      <%= link_to t('spree.new_bank'), new_object_url, id: 'admin_new_bank_link', class: 'btn btn-primary' %>
    </li>
  <% end %>
<% end %>

<%= paginate @banks, theme: "solidus_admin" %>

<% if @banks.present? %>
  <table class="index" id='listing_banks' data-hook>
    <thead>
      <tr data-hook="banks_header">
        <th><%= Spree.t(:bank_name) %></th>
        <th><%= Spree.t(:account_no) %></th>
        <th><%= Spree.t(:additional_details) %></th>
        <th><%= Spree.t(:status) %></th>
        <th class="actions" colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @banks.each do |bank|%>
        <tr id="<%= spree_dom_id bank %>" data-hook="banks_row">
          <td><%= bank.name %></td>
          <td><%= bank.account_no %></td>
          <td><%= bank.additional_details %></td>
          <td id='active-status-<%= bank.id %>'><%= bank_status(bank) %></td>
          <td data-hook="admin_banks_index_row_status" id='toggle-status-<%= bank.id %>' class="actions actions-2 text-right">
             <% action_class = bank.active ? "btn-danger" : "btn-success" %>
             <% btn_class = 'btn ' + action_class + ' btn-sm' %>
             <% status = bank.active ? "active" : "inactive" %>
             <% bank_id = 'bank-' + bank[:id].to_s %>
             <%= link_to_with_icon(action_text_to_toggle_bank_status(bank), action_to_toggle_bank_status(bank), toggle_activation_admin_bank_path(bank), {class: btn_class, id: bank_id, rel: status, remote: true, method: :put}) %>
          </td>
          <td class="actions">
            <% if can?(:update, bank) %>
              <%= link_to_edit bank %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Bank,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

app/views/spree/admin/banks/new.html.erb
<% admin_breadcrumb(t('spree.settings')) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::Bank), spree.admin_banks_path) %>
<% admin_breadcrumb(t('spree.new_zone')) %>

<% content_for :page_actions do %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @bank } %>

<%= form_for [:admin, @bank] do |bank_form| %>
  <%= render partial: 'form', locals: { bank_form: bank_form } %>

  <div class="clear"></div>

  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>

app/views/spree/admin/banks/toggle_activation.js.erb
<% if @success %>
  $('#active-status-<%= @bank.id %>').text('<%= bank_status(@bank) %>')
  <% action_class = @bank.active ? "btn-danger" : "btn-success" %>
  <% btn_class = "btn " + action_class + " btn-sm" %>
  <% status = @bank.active ? "active" : "inactive" %>
  <% bank_id = "bank-" + @bank[:id].to_s %>
  $('#toggle-status-<%= @bank.id %>').html('<%= link_to_with_icon(action_text_to_toggle_bank_status(@bank), action_to_toggle_bank_status(@bank), toggle_activation_admin_bank_path(@bank), {class: btn_class, id: bank_id, rel: status, remote: true, method: :put}) %>')
<% else %>
  alert('<%= @bank.errors.full_messages.to_sentence %>')
<% end %>

app/views/spree/checkout/payment/_banktransfer.html.erb
<% if @order.available_payment_methods.any? { |pm| pm.type == 'Spree::PaymentMethod::BankTransfer' } %>
  <p><%= link_to t(:how_bank_transfer_works), bank_transfer_instructions_path, id: 'banktransfer_instructions', target: "_blank" %></p>
<% end %>
<% if (banks = Spree::Bank.active).present? %>
  <table class="table index">
    <tr>
      <th><%= Spree.t(:bank_name) %></th>
      <th><%= Spree.t(:account_no) %></th>
      <th><%= Spree.t(:additional_details) %></th>
    </tr>
    <% banks.each do |bank| %>
      <tr>
        <td><%= bank.name %></td>
        <td><%= bank.account_no %></td>
        <td><%= bank.additional_details %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/spree/content/bank_transfer.html.erb
<h4>HOW BANK TRANSFER WORKS</h4>
<b>Steps:</b>
<ol>
  <li>Deposit order total in one of the below mentioned bank accounts. After this payment a payment reference number will be provided by the bank.
    <% if (banks = Spree::Bank.active).any? %>
      <div style="padding:20px 0">
      <table border="1" align='center' width="80%">
        <tr>
          <th><%= Spree.t(:bank_name) %></th>
          <th><%= Spree.t(:account_no) %></th>
          <th><%= Spree.t(:additional_details) %></th>
        </tr>
        <% banks.each do |bank| %>
          <tr>
            <td><center><%= bank.name %></center></td>
            <td><center><%= bank.account_no %></center></td>
            <td><center><%= bank.additional_details %></center></td>
          </tr>
        <% end %>
      </table>
      </div>
    <% end %>
  </li>
  <li>Enter this payment reference number on Order Details page by following steps:
    <ol style="padding:10px 0 0 20px" type='a'>
      <li>Go to "My Account" page.</li>
      <li>Select Order for which you want to provide details.</li>
      <li>Click on "Add Details" link visible in "Payment Information" column.</li>
      <li>Provide payment details and Submit.</li>
      <br><br>
      <%= image_tag 'payment_details.png' %>
    </ol>
  </li>
</ol>

app/views/spree/orders/_bank_transfer_form.html.erb
<% bank_transfer_payment = @order.payments.from_bank_transfer.first %>
<% if bank_transfer_payment && ['checkout', 'invalid'].exclude?(bank_transfer_payment.state) %>
  <% unless bank_transfer_payment.details_submitted? %>
    <br>
    <%= link_to Spree.t(:add_details), "javascript:void(0);", class: 'button add_bt_details' %>
  <% end %>
  <%= form_for bank_transfer_payment, html: { class: "bt_payment_form", style: "#{bank_transfer_payment.details_submitted? ? '' : 'display:none;'}" } do |f| %>
    <table>
      <tr>
        <td><%= Spree.t(:deposited_on) %></td><td><%= f.text_field :deposited_on, disabled: bank_transfer_payment.details_submitted?, class: 'required_field', 'field-name' => 'Deposited on' %></td>
      </tr>
      <tr>
        <td><%= Spree.t(:bank_name) %></td><td><%= f.text_field :bank_name, disabled: bank_transfer_payment.details_submitted?, class: 'required_field', 'field-name' => 'Bank name' %></td>
      </tr>
      <tr>
        <td><%= Spree.t(:account_no) %></td><td><%= f.text_field :account_no, disabled: bank_transfer_payment.details_submitted?, class: 'required_field', 'field-name' => 'Account No.' %></td>
      </tr>
      <tr>
        <td><%= Spree.t(:transaction_reference_no) %></td><td><%= f.text_field :transaction_reference_no, disabled: bank_transfer_payment.details_submitted?, class: 'required_field', 'field-name' => 'Transaction Reference No.' %></td>
      </tr>
    </table>
    <br>
    <% unless bank_transfer_payment.details_submitted? %>
      <%= f.submit "Submit", confirm: Spree.t(:confirm_details_submit)  %>
    <% end %>
  <% end %>
<% end %>


<% if I18n.locale != :en %>
  <%= javascript_include_tag "jquery-ui/datepicker-#{I18n.locale}" %>
<% end %>